#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENTITIES_DIR="${ROOT_DIR}/source/EntitiesMP"

if [[ ! -d "${ENTITIES_DIR}" ]]; then
  echo "generate_entitiesmp_headers: missing directory: ${ENTITIES_DIR}" >&2
  exit 1
fi

cat > "${ENTITIES_DIR}/Global.h" <<'EOF'
#ifndef SE_INCL_ENTITIESMP_GLOBAL_H
#define SE_INCL_ENTITIESMP_GLOBAL_H

// Generated by scripts/generate_entitiesmp_headers.sh.
// Keep this file deterministic in source control until the final .es compiler
// pipeline is wired for cross-platform builds.

enum EffectParticlesType { EPT_NONE = 0 };
enum SprayParticlesType { SPT_NONE = 0 };
enum EntityInfoBodyType { EIBT_NONE = 0 };
enum BoolEType { BET_FALSE = 0, BET_TRUE = 1 };
enum EventEType { EET_NONE = 0 };
enum DebrisParticlesType { DPT_NONE = 0 };
enum BasicEffectType { BFX_NONE = 0 };
enum SoundType { ST_NONE = 0 };
enum BulletHitType { BHT_NONE = 0 };

class CEntity;
class CModelInstance;

class CPlayerEntity : public CEntity {
public:
  void ChangeHairMesh(const CModelInstance&, int, int);
};

#endif
EOF

cat > "${ENTITIES_DIR}/Player.h" <<'EOF'
#ifndef SE_INCL_ENTITIESMP_PLAYER_H
#define SE_INCL_ENTITIESMP_PLAYER_H

// Generated by scripts/generate_entitiesmp_headers.sh.

#include <EntitiesMP/Global.h>

#endif
EOF

echo "generate_entitiesmp_headers: wrote ${ENTITIES_DIR}/Global.h and ${ENTITIES_DIR}/Player.h"
